version: '3'

services:
    express:
        environment: 
            HOME_CLOUD_STORAGE: /usr/src/app/storage
        ports:
            - "8081:5000"

    react:
        ports:
            - "8080:3000"
        depends_on: 
            - express
        stdin_open: true
